In [1]:
import numpy as np
from scipy.optimize import minimize

# Example data for w
w = np.array([0, 1, 1, 1, 8])  # Replace with your known vector
# N = len(w)  # Length of the vector

def project_omega(w, M = 1, w0 = 0.1, wN = 1.0):
    from scipy.optimize import minimize

    # Boundary conditions
    f_0 = w0
    f_N = wN

    assert M * (len(w) - 1) >= f_N, 'no feasiable solution'

    # Define the objective function (squared Euclidean norm)
    def objective(f):
        return np.sum((f - w)**2)

    # Define the constraint functions
    def boundary_0(f):
        return f[0] - f_0

    def boundary_N(f):
        return f[-1] - f_N

    def derivative_constraint(f):
        # Calculate the difference between adjacent values (finite difference)
        return -(np.max(np.abs(np.diff(f))) - M)
    
    def derivative_constraint_positive(f):
        # Calculate the difference between adjacent values (finite difference)
        return np.max(np.abs(np.diff(f)))

    # Initial guess for f
    f_init = w

    # Define constraints as a dictionary
    constraints = [
        {'type': 'eq', 'fun': boundary_0},  # f_0 = f_0
        {'type': 'eq', 'fun': boundary_N},  # f_N = f_N
        {'type': 'ineq', 'fun': derivative_constraint}  # f'(x) <= M,
        {'type': 'ineq', 'fun': derivative_constraint_positive}  # f'(x) <= M
    ]

    # Solve the optimization problem
    result = minimize(objective, f_init, constraints=constraints, method='SLSQP')

    return result.x, np.hstack([np.array([w0]),np.diff(result.x)])

    # Display the result
    print("Optimized f:", result.x)


In [2]:
project_omega(w, M = 1, w0 = 0.1, wN = 1.0)

(array([0.1, 1. , 1. , 1. , 1. ]), array([0.1, 0.9, 0. , 0. , 0. ]))

In [31]:
np.hstack([np.array([0.1]),np.diff(result.x)])

array([0.1       , 1.00021024, 0.99939099, 1.00022527, 1.0001735 ])

In [15]:
np.diff(result.x)

array([ 9.99973702e-01,  2.60241905e-05, -1.54285824e-06,  2.00000182e+00])